#!/bin/bash

/usr/bin/python3 /home/lhoyer/tensorflow/models/research/object_detection/train.py \
    --logtostderr \
    --pipeline_config_path=/media/data/Dokumente/Nextcloud/Studium/Bachelorarbeit/CNNRobotLocalisation/FirstStage/ssd_mobilenet2/exp1_background_diversity_swarmlab.config \
    --train_dir="/home/lhoyer/cnn_robot_localization/training/first_stage_2/ssd_mobilenet2/exp1/background_diversity_swarmlab/train_04/"
