#!/bin/bash

/usr/bin/python3 /home/lhoyer/tensorflow/models/research/object_detection/train.py \
    --logtostderr \
    --pipeline_config_path=/media/data/Dokumente/Nextcloud/Studium/Bachelorarbeit/CNNRobotLocalisation/FirstStage/ssd_mobilenet2/exp3_compositor_amount_20000.config \
    --train_dir="/home/lhoyer/cnn_robot_localization/training/first_stage_2/ssd_mobilenet2/exp3/compositor_amount_20000/train_03/"
