item {
  id: 36
  name: 'sphero_red'
}

item {
  id: 37
  name: 'sphero_yellow'
}

item {
  id: 38
  name: 'sphero_lime_green'
}

item {
  id: 39
  name: 'sphero_magenta'
}

item {
  id: 40
  name: 'sphero_purple'
}

item {
  id: 41
  name: 'sphero_green'
}

item {
  id: 42
  name: 'sphero_blue_green'
}

item {
  id: 49
  name: 'sphero_light_blue'
}

item {
  id: 50
  name: 'sphero_blue'
}

item {
  id: 51
  name: 'sphero_dark_blue'
}

item {
  id: 52
  name: 'sphero_dark_red'
}

item {
  id: 53
  name: 'sphero_dark_green'
}

item {
  id: 54
  name: 'sphero_white'
}
